# Generated by Django 4.2.3 on 2023-07-30 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_site', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='Body',
            new_name='body',
        ),
    ]
