# Generated by Django 4.2.3 on 2023-07-27 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='emai',
            field=models.EmailField(default=2, max_length=254),
            preserve_default=False,
        ),
    ]
