# Generated by Django 4.2.3 on 2023-07-27 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_post_emai'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='emai',
            new_name='email',
        ),
    ]
